### ISSUE TITLE
Testing all data records in a dataset

### ISSUE THREAD

**Issue by vruusmann** [selvinsource/spark-pmml-exporter-validator#1]
You have done great work! However, I can think of another way how to automate your testing process and make it more thorough.

The JPMML-Evaluator includes so-called integration testing modules for R/Rattle, KNIME and RapidMiner software. All test cases follow the same conventions. I think that you might consider applying these conventions to your project as well.

In brief, a test case consists of three resource files:
1) The PMML file that contains the predictive solution that needs to be tested.
2) Input data CSV file. This file contains one data column per each `active` or `group` mining field.
3) Output data CSV file. This file contains one data column per each `target` mining field and/or output field.

The module `pmml-evaluator` contains class `org.jpmml.evaluator.BatchUtil` that asserts that when the PMML file (`#1`) is executed with input data CSV file (`#2`), that then the actual predictions made by JPMML-Evaluator library match the expected predictions from the output data CSV file (`#3`).

In your case you have a static input data CSV file (`#2`) and dynamically generated PMML file (`#1`) and output data CSV file (`#3`). You could bind them all together the following way:

```
class SparkBatch implements Batch {
  private String id = null;

  public SparkBatch(String id){
    this.id = id;
  }

  // Implement methods #getModel, #getInput and #getOutput
}

Batch lassoRegression = new SparkBatch("lassoregression");

boolean success = BatchUtil.evaluate(lassoRegression);
if(!success){
  throw new AssertionError("Spark output does not match JPMML output");
}
```

I have written more about batch testing here:
http://openscoring.io/blog/2014/05/12/testing_pmml_applications/

**Comment by selvinsource** [comment]
Hi Villu,

I wasn't aware of the integration testing module of the JPMML Evaluator, I will certainly take a look and see if I can use it in addition to what I have done so far.

However, bear in mind that part of this project is learning to use JPMML Evaluator programmatically and this explains the approach taken.

Thanks,
Vincenzo

**Comment by nareshbab** [comment]
@selvinsource : Hi, I am trying to build this project but everytime I am running into same issue. Can you help me with the issue? The logs from command <code>mvn clean compile assembly:single</code> are as below:

naresh@ubuntu:~$ cd spark-pmml-exporter-validator/
naresh@ubuntu:~/spark-pmml-exporter-validator$ sparkvalidatorpath="$PWD"
naresh@ubuntu:~/spark-pmml-exporter-validator$ sparkshellpath="/home/naresh/spark-1.2.0-bin-hadoop2.4/bin/spark-shell"
naresh@ubuntu:~/spark-pmml-exporter-validator$ mvn clean compile assembly:single
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Spark PMML Exporter Validator 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/google/guava/guava/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/guava/guava/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/com/google/guava/guava/maven-metadata.xml (2 KB at 1.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/joda-time/joda-time/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/joda-time/joda-time/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/joda-time/joda-time/maven-metadata.xml (931 B at 0.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-math3/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/maven-metadata.xml (514 B at 0.7 KB/sec)
[INFO]  
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spark-pmml-exporter-validator ---
[INFO] Deleting /home/naresh/spark-pmml-exporter-validator/target
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ spark-pmml-exporter-validator ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 18 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ spark-pmml-exporter-validator ---
[INFO] Compiling 1 source file to /home/naresh/spark-pmml-exporter-validator/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.970s
[INFO] Finished at: Tue Jan 27 20:17:45 PST 2015
[INFO] Final Memory: 10M/45M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project spark-pmml-exporter-validator: Compilation failure: Compilation failure:
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[34,22] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,2] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,13] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,14] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,31] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,32] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,55] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,56] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,71] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,72] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,80] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,81] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,102] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,103] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,123] error: ';' expected
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[35,124] error: not a statement
[ERROR] 
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[79,2] error: annotations are not supported in -source 1.3
[ERROR] 
[ERROR](use -source 5 or higher to enable annotations)
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[93,35] error: generics are not supported in -source 1.3
[ERROR] 
[ERROR](use -source 5 or higher to enable generics)
[ERROR] /home/naresh/spark-pmml-exporter-validator/src/main/java/org/selvinsource/spark_pmml_exporter_validator/SparkPMMLExporterValidator.java:[157,28] error: for-each loops are not supported in -source 1.3
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by vruusmann** [comment]
@nareshbab Looks like you are using an outdated Java version (Java 1.3 or 1.4 perhaps?), because the compiler is complaining that it does not recognize enums (line 35), annotations (line 79) and generics (line 93).

However, if you are running Java 1.6 or newer, then you might have an issue with your Apache Maven configuration. You can instruct it to behave by adding the following maven-compiler-plugin declaration to the pom.xml file of this project:

``` xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.2</version>
  <configuration>
    <source>1.6</source>
    <target>1.6</target>
  </configuration>
</plugin>
```

**Comment by selvinsource** [comment]
@vruusmann 
thanks for your detailed answer, it does seem a Java version issue as you said.

**Comment by nareshbab** [comment]
@vruusmann Thanks a lot. For me it was maven compile issue. It would be of great help if you can point me where can I locate <code>org.apache.spark.mllib.export.ModelExporter</code> class. I am using spark-1.2.0-bin-hadoop-2.4 prebuilt but I am not able to find this particular class inside mllib folder, due to which I am not able to import it and execute the kmeans_iris.scala file in sparkshell. 

snippet of file is:
<code>import org.apache.spark.mllib.clustering.KMeans 
import org.apache.spark.mllib.linalg.Vectors 
import org.apache.spark.mllib.export.ModelExporter 
</code>

**Comment by vruusmann** [comment]
@nareshbab Normally you would search for a missing dependency by going to http://search.maven.org/, then clicking "Advanced Search", and theb performing the search "By Classname". Currently, it doesn't return any results for `org.apache.spark.mllib.export.ModelExporter`, which means that it's not publicly released yet.

You can find this class in Spark Pull Request 3062: https://github.com/apache/spark/pull/3062

So, you need to build this PR in your local machine in order to obtain this missing JAR file.

**Comment by selvinsource** [comment]
@nareshbab, to add to @vruusmann note, we are making some changes on how the export will work.

Instead of

```
import org.apache.spark.mllib.export.ModelExporter
val kmeansModel = ...
ModelExporter.toPMML(kmeansModel, "/path")
```

you will be able to do

```
val kmeansModel = ...
val pmml = kmeansModel.toPMML
```

I will update this project once we agreed on the new approach.

**Comment by selvinsource** [comment]
Updated scala examples to use the new approach of exporting models:
`model.toPMML("myfile.xml")` for all supported models and no need to import anything
